import { ReportItem, ThreatDetails, Device } from '../types';

export interface IncidentCsvRow {
  id: string;
  title: string;
  device: string;
  department: string;
  severity: string;
  status: string;
  detectedAt: string;
  action: string;
  sourceIp?: string;
  protocol?: string;
  riskScore?: number;
}

export const exportIncidentsToCsv = (incidents: IncidentCsvRow[], filenamePrefix = 'SentinelX_Incident_Report') => {
  if (!incidents || incidents.length === 0) return;

  const headers = [
    'Incident ID',
    'Threat Name',
    'Affected Device',
    'Department',
    'Severity',
    'Status',
    'Detection Time',
    'Response Action',
    'Source IP',
    'Protocol',
    'Risk Score'
  ];

  const rows = incidents.map(inc => {
    return [
      `"${(inc.id || '').replace(/"/g, '""')}"`,
      `"${(inc.title || '').replace(/"/g, '""')}"`,
      `"${(inc.device || 'Unassigned Device').replace(/"/g, '""')}"`,
      `"${(inc.department || 'IT Infrastructure').replace(/"/g, '""')}"`,
      `"${(inc.severity || 'Medium').replace(/"/g, '""')}"`,
      `"${(inc.status || 'Active').replace(/"/g, '""')}"`,
      `"${(inc.detectedAt || '').replace(/"/g, '""')}"`,
      `"${(inc.action || '').replace(/"/g, '""')}"`,
      `"${(inc.sourceIp || '10.0.0.1').replace(/"/g, '""')}"`,
      `"${(inc.protocol || 'TCP / HTTP').replace(/"/g, '""')}"`,
      `"${inc.riskScore ?? 75}"`
    ].join(',');
  });

  const csvContent = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filenamePrefix}_${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportReportsToCsv = (reports: ReportItem[], filenamePrefix = 'SentinelX_Security_Reports') => {
  if (!reports || reports.length === 0) return;

  const headers = [
    'Report ID',
    'Report Type',
    'Threat Name / Title',
    'Severity',
    'Affected Device',
    'Generated By',
    'Generated Time',
    'Status',
    'Mitigation Method',
    'Security Score',
    'Executive Summary'
  ];

  const rows = reports.map(r => {
    const execSummary = r.executiveSummary
      ? `${r.executiveSummary.currentSecurityPosture} ${r.executiveSummary.riskAssessment}`.replace(/"/g, '""')
      : (r.method || '').replace(/"/g, '""');

    return [
      `"${r.id}"`,
      `"${r.reportType || 'Daily'}"`,
      `"${(r.threatName || '').replace(/"/g, '""')}"`,
      `"${r.severity || 'Medium'}"`,
      `"${(r.affectedDevice || 'All Endpoints').replace(/"/g, '""')}"`,
      `"${(r.generatedBy || r.resolvedBy || 'SecOps AI').replace(/"/g, '""')}"`,
      `"${r.generatedTime || r.resolutionTime || ''}"`,
      `"${r.status || 'Resolved'}"`,
      `"${(r.method || '').replace(/"/g, '""')}"`,
      `"${r.snapshot?.securityScore || 90}"`,
      `"${execSummary}"`
    ].join(',');
  });

  const csvContent = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filenamePrefix}_${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportSingleReportToCsv = (report: ReportItem) => {
  exportReportsToCsv([report], `SentinelX_Report_${report.id}`);
};
